DROP TABLE IF EXISTS "user".user_has_coin;

CREATE TABLE "user".user_has_coin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    coin_id BIGINT NOT NULL,
    jumlah INT DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES "user".data_user(id)
  );
