DROP TABLE IF EXISTS "user".data_user;

CREATE TABLE "user".data_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(250) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password VARCHAR(50) NOT NULL,
    status VARCHAR(25) NOT NULL,
    is_active BOOLEAN default true,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
  );
